site_name: Kubil.us 
site_description: Information, tips, and other things I've stumbled across 
site_url: https://tech.kubil.us
docs_dir: blog
theme:
    name: rebalance
    google_adsense: ca-pub-0810613228728448 
    facebook_comment_appid: 749526962133490

plugins:
  - search
  - datesort
  - paginate:
      max_items: 9

social:
- type: 'github'
  link: 'https://github.com/kubilus1'

