site_name: Kubil.us 
site_description: Information, tips, and other things
site_url: https://tech.kubil.us
docs_dir: blog
theme:
    name: rebalance
    google_adsense: ca-pub-0810613228728448 
    facebook_comment_appid: 7136473109700609
    google_analytics: G-H60NPFK97F

plugins:
  - search
  - datesort
  - paginate:
      max_items: 9
  - mermaid2

extra:
  social:
  - type: 'github'
    link: 'https://github.com/kubilus1'
